steps:
  # Extract project name and version
  - name: 'ubuntu'
    id: 'extract-metadata'
    script: |
      #!/bin/bash
      PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml)
      VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' Cargo.toml)
      echo $PROJECT_NAME > /workspace/project_name.txt
      echo $VERSION > /workspace/version.txt
      echo "Extracted: PROJECT_NAME=$PROJECT_NAME, VERSION=$VERSION"

  # Build the Docker image using Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    script: |
      #!/bin/bash
      PROJECT_NAME=$(cat /workspace/project_name.txt)
      VERSION=$(cat /workspace/version.txt)
      docker build \
        --tag="europe-west1-docker.pkg.dev/giza-platform-common/agents/$PROJECT_NAME:$VERSION" \
        --tag="europe-west1-docker.pkg.dev/giza-platform-common/agents/$PROJECT_NAME:latest" \
        --file=Dockerfile \
        .
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    script: |
      #!/bin/bash
      PROJECT_NAME=$(cat /workspace/project_name.txt)
      docker push --all-tags "europe-west1-docker.pkg.dev/giza-platform-common/agents/$PROJECT_NAME"

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    script: |
      #!/bin/bash
      PROJECT_NAME=$(cat /workspace/project_name.txt)
      VERSION=$(cat /workspace/version.txt)

      # Generate a secure API key if not provided
      if [ -z "$_API_KEY" ]; then
        API_KEY=$(openssl rand -hex 32)
        echo "Generated API Key: $API_KEY"
      else
        API_KEY="$_API_KEY"
      fi
      
      gcloud run deploy "$PROJECT_NAME" \
        --image="europe-west1-docker.pkg.dev/giza-platform-common/agents/$PROJECT_NAME:$VERSION" \
        --region=europe-west1 \
        --platform=managed \
        --memory=4Gi \
        --cpu=2 \
        --timeout=300 \
        --max-instances=10 \
        --cpu-boost \
        --execution-environment=gen2 \
        --set-env-vars=MAX_UPLOAD_SIZE_MB=100,RUST_BACKTRACE=1,API_KEY="$API_KEY" \
        --allow-unauthenticated

substitutions:
  _API_KEY: ''

timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY