steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/rekt-recommender-api:$COMMIT_SHA'
      - '--tag=gcr.io/$PROJECT_ID/rekt-recommender-api:latest'
      - '--file=Dockerfile'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/rekt-recommender-api'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rekt-recommender-api'
      - '--image=gcr.io/$PROJECT_ID/rekt-recommender-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=4Gi'
      - '--cpu=2'
      - '--timeout=300'
      - '--max-instances=10'
      - '--cpu-boost'
      - '--execution-environment=gen2'
      - '--set-env-vars=MAX_UPLOAD_SIZE_MB=100,RUST_BACKTRACE=1'
      - '--allow-unauthenticated'

timeout: 1200s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY